# Generated by Django 3.0.7 on 2020-07-09 13:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('short_desc', models.CharField(max_length=100)),
                ('decription', models.TextField(max_length=1000)),
                ('image1', models.ImageField(upload_to='')),
                ('image2', models.ImageField(upload_to='')),
                ('category', models.CharField(choices=[('p', 'POLITICS'), ('y', 'YOUTH'), ('e', 'ENTERTAINMENT'), ('c', 'COVID-19'), ('t', 'TRENDING'), ('r', 'REVIEWS')], default=0, max_length=1)),
                ('trending', models.CharField(choices=[('td', 'TRENDING TODAY '), ('tp', 'TOP TRENDING'), ('no', 'None')], default=0, max_length=2)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image_slider', models.ImageField(upload_to='')),
            ],
        ),
    ]
