# Generated by Django 3.0.8 on 2020-07-19 16:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=60)),
                ('head_desc', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=500)),
                ('short_desc', models.CharField(max_length=1000)),
                ('image', models.CharField(max_length=500)),
                ('decription', models.TextField(max_length=5000)),
                ('twitter', models.CharField(blank=True, max_length=300)),
                ('youtube', models.CharField(blank=True, max_length=1000)),
                ('img', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True, max_length=5000)),
                ('category', models.CharField(choices=[('news', 'NEWS'), ('youth', 'YOUTH'), ('entertainment', 'ENTERTAINMENT'), ('games', 'GAMES'), ('world', 'WORLD'), ('reviews', 'REVIEWS')], default=0, max_length=13)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviews_tag', models.CharField(choices=[(' ', ' '), ('MOVIES', 'MOVIES'), ('SERIES', 'SERIES'), ('ANIME', 'ANIME')], default=0, max_length=6)),
                ('keyword', models.CharField(max_length=60)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='read',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('image', models.CharField(max_length=500)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('image_size_950x280', models.CharField(max_length=500)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='trending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('image', models.CharField(max_length=500)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
