# Generated by Django 3.0.7 on 2020-07-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='decription',
            field=models.TextField(max_length=2000),
        ),
    ]
