# Generated by Django 3.0.8 on 2020-07-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='head',
            field=models.CharField(max_length=66),
        ),
        migrations.AlterField(
            model_name='news',
            name='head_desc',
            field=models.CharField(max_length=157),
        ),
    ]
