# Generated by Django 3.0.8 on 2020-07-19 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200719_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='head',
        ),
        migrations.RemoveField(
            model_name='news',
            name='head_desc',
        ),
    ]
