# Generated by Django 3.0.7 on 2020-07-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200709_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='short_desc',
            field=models.CharField(max_length=500),
        ),
    ]
