# Generated by Django 3.0.7 on 2020-07-09 14:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200709_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
