# Generated by Django 3.0.7 on 2020-07-09 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20200709_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
