# Generated by Django 3.0.7 on 2020-07-10 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20200710_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
