# Generated by Django 3.0.7 on 2020-07-10 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_slider_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slider',
        ),
        migrations.AddField(
            model_name='news',
            name='slider',
            field=models.BooleanField(default=False),
        ),
    ]
