# Generated by Django 3.0.8 on 2020-07-12 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20200710_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='image2',
        ),
        migrations.AlterField(
            model_name='news',
            name='decription',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='news',
            name='short_desc',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
