# Generated by Django 3.0.8 on 2020-07-12 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_news_twitter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='twitter',
        ),
    ]
