# Generated by Django 3.0.8 on 2020-07-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_remove_news_twitter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
