# Generated by Django 3.0.8 on 2020-07-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_auto_20200712_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('image1', models.ImageField(upload_to='')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
