# Generated by Django 3.0.8 on 2020-07-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_auto_20200712_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('p', 'NEWS'), ('y', 'YOUTH'), ('e', 'ENTERTAINMENT'), ('c', 'COVID-19'), ('t', 'WORLD'), ('r', 'REVIEWS')], default=0, max_length=1),
        ),
    ]
