# Generated by Django 3.0.8 on 2020-07-13 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_auto_20200713_0041'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='top_trending',
            new_name='news2',
        ),
        migrations.RenameModel(
            old_name='trending_today',
            new_name='trending',
        ),
    ]
