# Generated by Django 3.0.8 on 2020-07-13 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_auto_20200713_1326'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='news2',
            new_name='read',
        ),
    ]
