# Generated by Django 3.0.8 on 2020-07-14 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0020_auto_20200714_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='read',
            name='image',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image_size_950x280',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='trending',
            name='image',
            field=models.CharField(max_length=500),
        ),
    ]
