# Generated by Django 3.0.8 on 2020-07-14 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0021_auto_20200714_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='youtube',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
