# Generated by Django 3.0.8 on 2020-07-15 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0022_news_youtube'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='description',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='news',
            name='decription',
            field=models.TextField(max_length=5000),
        ),
    ]
