# Generated by Django 3.0.8 on 2020-07-15 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0023_auto_20200715_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='reviews_tag',
            field=models.CharField(choices=[('n', ' '), ('m', 'MOVIES'), ('s', 'SERIES')], default=0, max_length=1),
        ),
    ]
