# Generated by Django 3.0.8 on 2020-07-15 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0024_news_reviews_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='reviews_tag',
            field=models.CharField(choices=[(' ', ' '), ('MOVIES', 'MOVIES'), ('SERIES', 'SERIES')], default=0, max_length=6),
        ),
    ]
