# Generated by Django 3.0.8 on 2020-07-15 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0025_auto_20200715_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('p', 'NEWS'), ('y', 'YOUTH'), ('e', 'ENTERTAINMENT'), ('c', 'GAMES'), ('t', 'WORLD'), ('r', 'REVIEWS')], default=0, max_length=1),
        ),
    ]
