# Generated by Django 3.0.8 on 2020-07-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0026_auto_20200715_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='reviews_tag',
            field=models.CharField(choices=[(' ', ' '), ('MOVIES', 'MOVIES'), ('SERIES', 'SERIES'), ('ANIME', 'ANIME')], default=0, max_length=6),
        ),
    ]
