# Generated by Django 3.0.8 on 2020-07-16 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0028_news_twitter'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='img',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
