# Generated by Django 3.0.8 on 2020-07-17 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0029_news_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('news', 'NEWS'), ('youth', 'YOUTH'), ('entertainment', 'ENTERTAINMENT'), ('games', 'GAMES'), ('world', 'WORLD'), ('reviews', 'REVIEWS')], default=0, max_length=13),
        ),
    ]
