# Generated by Django 3.0.8 on 2020-07-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0030_auto_20200717_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='keyword',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
