# Generated by Django 3.0.8 on 2020-07-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0034_auto_20200719_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='head',
            field=models.CharField(max_length=60),
        ),
    ]
