# Generated by Django 3.0.8 on 2020-07-19 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0035_auto_20200719_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='keyword',
        ),
    ]
