# Generated by Django 3.0.8 on 2020-07-20 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0037_auto_20200719_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='keyword',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='head',
            field=models.CharField(max_length=66),
        ),
        migrations.AlterField(
            model_name='news',
            name='head_desc',
            field=models.CharField(max_length=157),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
